spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/vollmed_api
    username: rafaelrenaud
    password: postgres
  jpa:
    show-sql: true

server:
  error:
    include-stacktrace: never
  security:
    tokenSecret: 123456